package main

const (
	PLS_SP_AUTH             = "Please specify authentication token."
	PLS_SP_REDIS_HOST       = "Please specify redis host."
	PLS_SP_RABBITMQ_USR     = "Please specify rabbitmq user."
	PLS_SP_RABBITMQ_HOST    = "Please specify rabbitmq host."
	PLS_SP_RABBITMQ_VHOST   = "Please specify rabbitmq vhost."
	PLS_TRY_LATER           = "An error occurred. Please try again later, or contact support at info@elliman.com"
	USER_NOT_CREATED        = "User not created, please try again later"
	EMAIL_EXISTS            = "This email account already exists. Please log in"
	USER_NOT_UPDATED        = "User not updated, please try again later"
	USER_EXP_NOT_UPDATED    = "User password expiration date not updated, please try again later"
	CANT_GET_USER_LISTINGS  = "Can not get user listings, please try again later"
	CANT_GET_LISTING        = "Can not get listing, please try again later"
	CANT_GET_FOLDER         = "Can not get folder, please try again later"
	LST_NOT_SAVED           = "Unable to save the listing at this time, please try again later"
	LST_ALREADY_SAVED       = "This listing already saved in this folder"
	RABBITMQ_TASKS_QUEUE    = "elliman_go_tasks_"
	PLS_FILL_FIELDS         = "Please fill out the required fields: "
	INVALID_PASSWORD        = "Your password does not meet the requirements. Please select a password that is at least 4 characters"
	LST_NOT_FOUND           = "Listing not found"
	FOLDER_NOT_FOUND        = "Folder not found"
	USER_NOT_FOUND          = "Please try again later, or contact support at info@elliman.com"
	INCORRECT_EMAIL_OR_PASS = "Incorrect Email or Password"
	EMAIL_NOT_VERIFIED      = "Email not verified"
	ACC_HAS_EXPIRED         = "Account has expired"
)
